---
title: "Work Experience"

---
<br>
<b>PERRY INSTITUTE OF MARINE SCIENCE</b> <i>New Providence, The Bahamas</i>

<i>Community Conservation Education & Action Intern, June 2023 – August 2023</i>
<p>
<ul>
  <li>Gathered and analyzed data for research on the impact of Covid-19 on subsistence fishing in The Bahamas.</li>
  <li>Inductive coding and data analysis of approximately 29 survey respondents and 26 interview respondents.</li>
  <li>Taught lessons on local coastal ecosystem threats and conservation to a cohort of 5 high school students.</li>
  <li>Led students in snorkeling field activities to explore seagrass beds and coral reefs.</li>
  <li>Curated 3 social media posts for the Perry Institute’s pages, on the resilience of subsistence fishing during social and 
environmental disturbances.</li>
</ul> </p>
<br>

<p> 
<b>UNIVERSITY OF MIAMI ROSENSTIEL UNDERGRADUATE OFFICE</b> <i>Coral Gables, Florida, USA</i>

<i>Office Assistant, August 2022 – Present</i>
<p>
<ul>
  <li>Assist with creating a welcoming office atmosphere through daily office upkeep.</li>
  <li>Engage and communicate with prospective undergraduate students and families.</li>
  <li>Taught lessons on local coastal ecosystem threats and conservation to a cohort of 5 high school students.</li>
  <li>Distribute important daily communications to the Rosenstiel School of Marine, Atmospheric & Earth science students, faculty members and advisors.</li>
  <li>Planning and reserving spaces for Rosenstiel events throughout the academic year.</li>
</ul>
</p>
<br>

<p>
<b>BAHAMAS MARINE MAMMAL RESEARCH ORGANIZATION</b> <i>Abaco, The Bahamas</i>
<p>
<i>Research Intern, June 2022 - July 2022</i> 
<ul>
  <li>Assisted with identification, photography, and biopsying of Blainville’s beaked whales and sperm whales.</li>
  <li>Logged daily ship data, and downloaded GPS waypoints for each excursion.</li>
  <li>Participated in hurricane disaster preparedness training with Friends of the Environment.</li>
  <li>Organized and cleaned equipment and office areas daily.</li>
</ul>
</p>

<br>
<h1>Volunteer Experience </h1><br>

<p>
<b>NORTH ATLANTIC RIGHT WHALE PhD RESEARCH </b> <i>Coral Gables, Florida, USA</i>
<p>
<i>Research Assistant, February 2023 - May 2023</i> 
<ul>
  <li>Performed deductive coding of over 400 news articles.</li>
  <li>Assisted with inter-coder agreement and reliability tests.</li>
  <li>Recommend valuable improvements to the codebook.</li>
 </ul>
</p>

<br>
<b>BLUE LAGOON ISLAND TREE PLANTING </b> <i>New Providence, The Bahamas</i>
<p>
<i>Volunteer, March 2020</i> 
<ul>
  <li>Collected and transplanted seedlings as a part of the 1- million tree planting initiative.</li>
  <li>Potted over 500 seagrapes and 70 mangroves and planted 68 seagrape seedlings.</li>
 </ul>
</p>
